### ISSUE TITLE
"Chose a form" Window is too small to fit any content

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#430]
On a data insertion tab in Specify 6.8.00 on macOS, there is a button "More forms"
<img width="528" alt="Screen Shot 2019-11-29 at 1 23 18 PM" src="https://user-images.githubusercontent.com/40512816/69887383-4173bb80-12ac-11ea-8ccc-faa13e6ae574.png">

Normally, the click on this button opens the "Chose a form" window, which should look like that
<img width="528" alt="Screen Shot 2019-11-29 at 1 23 54 PM" src="https://user-images.githubusercontent.com/40512816/69887269-b8f51b00-12ab-11ea-92a1-c1d2376b1f43.png">

But also sometimes is displayed like that:

<img width="528" alt="Screen Shot 2019-11-29 at 1 23 44 PM" src="https://user-images.githubusercontent.com/40512816/69887279-c4e0dd00-12ab-11ea-8023-2a4c405913db.png">

It seemed at first like it can not fetch any tables, but in reality, the window is just to short to fit any content. User can increase the height of the window manually, or click a fullscreen button to solve this issue, though the user is far more likely to think that there are no "More forms" available

The issues occur seemingly randomly without particular consistency: I can click the button 10 times, and 5 of them will be showing the window of normal size, whereas other 5 would show an ultra-short window

A possible solution would be to set the minimum height for the window and is such a way to prevent the user or the system from summoning a window that is too short

I am not sure, but the problem seems to be specific to macOS systems. Also, it fixes itself after the reboot of Specify but then can occur again for seemingly no apparent reason. Tell me if more research and testing is needed to identify the possible cause of this bug

**Comment by maxxxxxdlp** [comment]
Similar problem with "Updating tree" window, except in this case the user can not change the size of the window, to properly fit the content

<img width="528" alt="Screen Shot 2019-11-29 at 1 53 19 PM" src="https://user-images.githubusercontent.com/40512816/69888078-a11f9600-12af-11ea-8785-95486e8ae783.png">

**Comment by maxxxxxdlp** [comment]
Same problem with "Chose a Record Set" Window (Workbench > Create a Data Set from Record Set)

<img width="1440" alt="Screen Shot 2019-11-29 at 2 32 35 PM" src="https://user-images.githubusercontent.com/40512816/69889165-222d5c00-12b5-11ea-8656-6d464a8a7f2e.png">

This is how it is supposed to look, even if there are no record sets available to chose from:
<img width="362" alt="Screen Shot 2019-11-29 at 2 34 20 PM" src="https://user-images.githubusercontent.com/40512816/69889205-56a11800-12b5-11ea-81cf-c62dfe871359.png">

**Comment by maxxxxxdlp** [comment]
Still is a problem for Tree updates window

<img width="322" alt="Screen Shot 2019-12-04 at 10 19 39 AM" src="https://user-images.githubusercontent.com/40512816/70160142-a00bb180-167f-11ea-96f0-2500fa76fdcc.png">

**Comment by maxxxxxdlp** [comment]
Still the case for `Choose a Record Set`

<img width="405" alt="Screen Shot 2019-12-04 at 10 21 34 AM" src="https://user-images.githubusercontent.com/40512816/70160279-dba67b80-167f-11ea-9d19-96cd2c9e30e8.png">

**Comment by maxxxxxdlp** [comment]
@timo11  need to take another look at this issue

**Comment by timo11** [comment]
This was fixed 12/3. Are you running from the ide or are you using v6.8.00_testing_20191202?

**Comment by maxxxxxdlp** [comment]
Am running the latest beta of Specify (v6.8.00_testing_20191202)

<img width="1440" alt="Screen Shot 2019-12-04 at 12 31 52 PM" src="https://user-images.githubusercontent.com/40512816/70170305-10bbc980-1692-11ea-8fbd-091f5cd519b8.png">

<img width="1440" alt="Screen Shot 2019-12-04 at 12 30 42 PM" src="https://user-images.githubusercontent.com/40512816/70170227-e5d17580-1691-11ea-8d8a-69ef351bb7fa.png">

**Comment by maxxxxxdlp** [comment]
All bugs are reproducible

<img width="1440" alt="Screen Shot 2019-12-04 at 12 32 49 PM" src="https://user-images.githubusercontent.com/40512816/70170376-30eb8880-1692-11ea-98e2-b448cd6e725a.png">

**Comment by timo11** [comment]
The fix from 12/3 is not in the release from 12/2

**Comment by maxxxxxdlp** [comment]
Okay. Am sorry about that. Will test it in the next release

**Comment by maxxxxxdlp** [comment]
`Updating Tree` window does work well now
All the other windows are still broken (30% of the time)

<img width="1440" alt="Screen Shot 2019-12-04 at 4 52 50 PM" src="https://user-images.githubusercontent.com/40512816/70188705-065ff680-16b7-11ea-976d-e413bc6f4d22.png">
<img width="1440" alt="Screen Shot 2019-12-04 at 4 53 39 PM" src="https://user-images.githubusercontent.com/40512816/70188706-06f88d00-16b7-11ea-97c4-2988aba6f3a5.png">
<img width="1440" alt="Screen Shot 2019-12-04 at 4 55 00 PM" src="https://user-images.githubusercontent.com/40512816/70188707-06f88d00-16b7-11ea-8b1c-311bac78846e.png">

**Comment by timo11** [comment]
All windows were sized properly 10+/10+ displays.
Seems, for me, that the issue was more likely to occur after swtiching to Specify from another app, and after using the close box rather than the cancel btn.

**Comment by maxxxxxdlp** [comment]
Reproducible in the newest beta if I close the window before this one by both cancel button and red X in the corner
Thought now it happens not in 50% of cases, but only in one in 30. **Good enough?**
I just can not comprehend why is this issue occurring at random
Also, the window usually opens at the middle of the screen, but sometimes it spawns in a location different than that (may be connected)

<img width="1440" alt="Screen Shot 2019-12-05 at 3 59 28 PM" src="https://user-images.githubusercontent.com/40512816/70277551-39b68a00-1778-11ea-8596-d12930b52aa9.png">
<img width="1440" alt="Screen Shot 2019-12-05 at 3 56 17 PM" src="https://user-images.githubusercontent.com/40512816/70278061-28ba4880-1779-11ea-8866-6b274f90a676.png">

**Comment by tlammer** [comment]
also, on a PC, when I click to see the error log, the window expands past both of my screens.  I have to move it to get to an edge to resize it.
To test this, I'm sure you will need to have created an error earlier so there is a stack trace error in the text.

**Comment by tlammer** [comment]
also, this happens:
![image](https://user-images.githubusercontent.com/12532430/70360384-ef9ada80-1843-11ea-85bb-7d8189125796.png)

**Comment by maxxxxxdlp** [comment]
Linux here
Error window wider that the screen
Errror is summoned by entering incorect IT Username and IT Passwrd

![Screenshot from 2019-12-09 14-02-44](https://user-images.githubusercontent.com/40512816/70468461-bf924800-1a8c-11ea-86ab-752b9f799bbc.png)

**Comment by maxxxxxdlp** [comment]
Even though this one does not occur in Specify 6.8 on my screen, it still can, depending on how wide user's screen is. Specify should limit maximum width of error window to the width of a screen and use word wrap for text inside
![Screenshot from 2019-12-09 14-07-02](https://user-images.githubusercontent.com/40512816/70468715-34658200-1a8d-11ea-98f1-54607692be61.png)

**Comment by maxxxxxdlp** [comment]
Still happening
<img width="1440" alt="Screen Shot 2019-12-12 at 3 53 02 PM" src="https://user-images.githubusercontent.com/40512816/70752729-cfae5f80-1cf8-11ea-96cc-4773abed39d3.png">
<img width="1440" alt="Screen Shot 2019-12-12 at 4 01 22 PM" src="https://user-images.githubusercontent.com/40512816/70752731-cfae5f80-1cf8-11ea-9a9e-bdd8f18b3114.png">
<img width="1440" alt="Screen Shot 2019-12-12 at 4 02 03 PM" src="https://user-images.githubusercontent.com/40512816/70752732-cfae5f80-1cf8-11ea-9341-572db074f6ef.png">

Choose a record set took ~50 times opening/closing the windows to replicate the issue, but still happens

**Comment by maxxxxxdlp** [comment]
The window to chose a collection usually opens normally, but this time it did not
<img width="1141" alt="Screen Shot 2019-12-13 at 11 01 25 AM" src="https://user-images.githubusercontent.com/40512816/70817811-fec7de00-1d97-11ea-83ea-4e4fd204adbe.png">
I think that every window in Specify on macOS can get opened with inappropriate size from time to time

**Comment by maxxxxxdlp** [comment]
The window to chose a collection usually opens normally, but this time it did not
<img width="1141" alt="Screen Shot 2019-12-13 at 11 01 25 AM" src="https://user-images.githubusercontent.com/40512816/70817811-fec7de00-1d97-11ea-83ea-4e4fd204adbe.png">
I think that every window in Specify on macOS can get opened with inappropriate size from time to time

**Comment by maxxxxxdlp** [comment]
The window to chose a collection usually opens normally, but this time it did not
<img width="1141" alt="Screen Shot 2019-12-13 at 11 01 25 AM" src="https://user-images.githubusercontent.com/40512816/70817811-fec7de00-1d97-11ea-83ea-4e4fd204adbe.png">
I think that every window in Specify on macOS can get opened with inappropriate size from time to time

**Comment by maxxxxxdlp** [comment]
The window to chose a collection usually opens normally, but this time it did not
<img width="1141" alt="Screen Shot 2019-12-13 at 11 01 25 AM" src="https://user-images.githubusercontent.com/40512816/70817811-fec7de00-1d97-11ea-83ea-4e4fd204adbe.png">
I think that every window in Specify on macOS can get opened with inappropriate size from time to time

**Comment by timo11** [comment]
I can't duplicate this issue on my mac.

**Comment by timo11** [comment]
It would also be a good idea to see if the problem occurs with java 9,10,11.

**Comment by maxxxxxdlp** [comment]
Tested and successfuly reproduced in VMs:
macOS 10.15 with latest Specify 6.8 beta, clean database, Amazon Correto 8, mysql 5.7
macOS 10.14 with latest Specify 6.8 beta, clean database, Amazon Correto 8, mysql 5.7
macOS 10.13 with latest Specify 6.8 beta, clean database, Amazon Correto 8, mysql 5.7

**Comment by timo11** [comment]
What about later java versions?

**Comment by timo11** [comment]
Probably not actually fixed. But redundant, possibly questionable code was re-done for the Choose-Collection dialog, Updating-Tree progress dialog, and the Choose-Recordset dialog, so those dialogs should be tested.

**Comment by maxxxxxdlp** [comment]
"Updating Geography tree" window is sized perfectly (tested 5 times)
"Chose a RecordSet" window is sized perfectly (tested ~250 times)

"Chose a Form" - is still broken sometimes
<img width="1440" alt="Screen Shot 2019-12-19 at 10 51 35 AM" src="https://user-images.githubusercontent.com/40512816/71192724-78574480-224e-11ea-8cf4-2d1cba84c6d3.png">

Tested in Specify 6.8 latest beta (12/19/2019) with a freshly created database on macOS Catalina

**Comment by timo11** [comment]
What about the Choose Collection dialog for changing collections?
I will look at the Choose Form dlg.

**Comment by maxxxxxdlp** [comment]
`"Chose Collection"` opens in one of those sizes:

<img width="562" alt="Screen Shot 2019-12-19 at 11 18 56 AM" src="https://user-images.githubusercontent.com/40512816/71194376-6dea7a00-2251-11ea-918b-5787d799de63.png">
<img width="562" alt="Screen Shot 2019-12-19 at 11 18 45 AM" src="https://user-images.githubusercontent.com/40512816/71194377-6dea7a00-2251-11ea-9f58-258c1f29f7fb.png">
<img width="562" alt="Screen Shot 2019-12-19 at 11 18 40 AM" src="https://user-images.githubusercontent.com/40512816/71194378-6dea7a00-2251-11ea-8f96-6691884ef338.png">

**Comment by maxxxxxdlp** [comment]
Have just gotten such 'beauty':
<img width="1440" alt="Screen Shot 2019-12-19 at 11 30 32 AM" src="https://user-images.githubusercontent.com/40512816/71195174-03d2d480-2253-11ea-9af0-2f701be9ddcb.png">

**Comment by timo11** [comment]
streamlined sizing of choose collection dialog. maybe it will work on max's mac.
Also, my mac which has not had form sizing issues since 12/13 is running Sun Java 1.8.

**Comment by maxxxxxdlp** [comment]
All of the previous issues seem to be fixed now

Here is one more problem with windows:
<img width="1440" alt="Screen Shot 2019-12-23 at 3 06 11 PM" src="https://user-images.githubusercontent.com/40512816/71380702-dd37d500-2595-11ea-96e5-362bcae8e26f.png">
Originaly found by Andy 
The main window of specify opens in its minimum size

How it happened:
Created new Discipline for an existing database
Chosen a previously created collection when logging in
(may not be connected to this and be happening just at random as previous issues did)

Andy also reported that it happens for him for freshly installed Specify instances

**Comment by maxxxxxdlp** [comment]
Data > Right Click on the left panel > Configure

<img width="1440" alt="Screen Shot 2019-12-27 at 4 12 45 PM" src="https://user-images.githubusercontent.com/40512816/71534333-c4942b80-28c3-11ea-86d5-aa42fdc976cf.png">

**Comment by maxxxxxdlp** [comment]
Query > Right Clcik on the left panel > Configure Query Creators
<img width="1440" alt="Screen Shot 2019-12-27 at 4 13 52 PM" src="https://user-images.githubusercontent.com/40512816/71534350-e1c8fa00-28c3-11ea-8ffe-d36159cb43e6.png">

Query > Right Click on the left panel > Configure Saved Queries
Usually opens like this, which is not normal
<img width="1440" alt="Screen Shot 2019-12-27 at 4 15 08 PM" src="https://user-images.githubusercontent.com/40512816/71534395-340a1b00-28c4-11ea-9615-80546cebc7d5.png">
Sometimes opens like this:
<img width="1440" alt="Screen Shot 2019-12-27 at 4 16 02 PM" src="https://user-images.githubusercontent.com/40512816/71534396-340a1b00-28c4-11ea-99e7-2a10c1f16362.png">

**Comment by maxxxxxdlp** [comment]
`Query > Right click on left panel > Configure Query Creators`
![Screen Shot 2020-01-02 at 12 34 27 PM](https://user-images.githubusercontent.com/40512816/71684834-39e87c00-2d5c-11ea-99e0-b792526c9d18.png)

**Comment by maxxxxxdlp** [comment]
Also, the `Batch Editor` window usually appears at the middle of the screen, but in some cases it appears in the lower right corner of the screen. Though, this is not a huge problem as the user can move the window in this case

![Screen Shot 2020-01-07 at 5 12 06 PM](https://user-images.githubusercontent.com/40512816/71942187-406a5f80-3171-11ea-9829-68b3404826d1.png)

It is just weird that there are inconsistencies in the places where windows can get open and which may cause bigger problems in some cases

**Comment by timo11** [comment]
Fixed again a little.

I never saw shrunken any windows, but the cut-off right section of the configure saved queries dlg seems to have been fixed. 

Also, in the Configure Forms dlg, the '+' buttons were opening ToggleBtnDlgs behind the Configure Form Dlg in Mac OS, and that problem should be solved. #401

**Comment by maxxxxxdlp** [comment]
Tested in [v6.8.00_testing_rc_20200224](https://github.com/specify/specify6/releases/tag/untagged-015bd4e83fd1d6090ced)

Had problems with the following windows:

<img width="405" alt="Screen Shot 2020-02-24 at 5 29 19 PM" src="https://user-images.githubusercontent.com/40512816/75200826-669d8c00-572c-11ea-902b-7a53cacc24f6.png">

<img width="612" alt="Screen Shot 2020-02-24 at 5 29 51 PM" src="https://user-images.githubusercontent.com/40512816/75200830-67362280-572c-11ea-9231-3e09a3b236bb.png">

---

Did not have any problems with the following windows (done ~20 test on each):
<img width="353" alt="Screen Shot 2020-02-24 at 5 33 51 PM" src="https://user-images.githubusercontent.com/40512816/75200855-7d43e300-572c-11ea-8f55-314a0db21b72.png">
<img width="352" alt="Screen Shot 2020-02-24 at 5 33 40 PM" src="https://user-images.githubusercontent.com/40512816/75200857-7e751000-572c-11ea-91ee-2e94beda3d44.png">
<img width="322" alt="Screen Shot 2020-02-24 at 5 26 24 PM" src="https://user-images.githubusercontent.com/40512816/75200860-7fa63d00-572c-11ea-80fc-31881301c5ed.png">
<img width="348" alt="Screen Shot 2020-02-24 at 5 24 22 PM" src="https://user-images.githubusercontent.com/40512816/75200862-7fa63d00-572c-11ea-8490-cfb664015371.png">
<img width="412" alt="Screen Shot 2020-02-24 at 5 23 48 PM" src="https://user-images.githubusercontent.com/40512816/75200864-803ed380-572c-11ea-8c1b-fd3637a1254f.png">
<img width="411" alt="Screen Shot 2020-02-24 at 5 21 05 PM" src="https://user-images.githubusercontent.com/40512816/75200865-80d76a00-572c-11ea-84fb-f510d0c3dbf6.png">
<img width="335" alt="Screen Shot 2020-02-24 at 5 19 22 PM" src="https://user-images.githubusercontent.com/40512816/75200866-80d76a00-572c-11ea-9a25-5fbad2e9de4d.png">
<img width="335" alt="Screen Shot 2020-02-24 at 5 17 46 PM" src="https://user-images.githubusercontent.com/40512816/75200868-81700080-572c-11ea-9f53-a9e1be2ed349.png">

---

Unable to replicate [this](https://github.com/specify/specify6/issues/430#issuecomment-568582407), though I would suppose it still happens because it used to apear quite rarely

**Comment by maxxxxxdlp** [comment]
Normal size of the `Configure Interactions SideBar` window
<img width="655" alt="Screen Shot 2020-02-25 at 9 17 00 AM" src="https://user-images.githubusercontent.com/40512816/75260741-ae192c00-57af-11ea-8b1f-3905b89f9bb4.png">

Sometimes it looks lke this
<img width="655" alt="Screen Shot 2020-02-25 at 9 16 56 AM" src="https://user-images.githubusercontent.com/40512816/75260739-ad809580-57af-11ea-877e-b4b60e713929.png">

And sometimes like this
<img width="405" alt="Screen Shot 2020-02-25 at 9 17 13 AM" src="https://user-images.githubusercontent.com/40512816/75260742-ae192c00-57af-11ea-91e0-c958c3e8a446.png">

**Comment by maxxxxxdlp** [comment]
Also this
<img width="423" alt="Screen Shot 2020-02-27 at 10 33 40 AM" src="https://user-images.githubusercontent.com/40512816/75464457-d68a5d00-594c-11ea-83c9-44a425ab1ce5.png">

**Comment by maxxxxxdlp** [comment]
Originally reported by Andy

This still happens (specify opens in a very small window)

<img width="670" alt="Screen Shot 2020-03-06 at 3 07 41 PM" src="https://user-images.githubusercontent.com/40512816/76122701-4d160300-5fbc-11ea-953c-8a55f923bf2a.png">

**Comment by maxxxxxdlp** [comment]
I got this bug 5 times in a row. I guess I am really lucky
<img width="311" alt="Screen Shot 2020-03-27 at 12 13 33 PM" src="https://user-images.githubusercontent.com/40512816/77781951-73134e00-7024-11ea-8722-772f3c4cd5fb.png">

**Comment by maxxxxxdlp** [comment]
Got this to happen again. Did not reinstall Specify or recreate the database recently. I guess it happens completely randomly

![image](https://user-images.githubusercontent.com/40512816/80133539-ff9d2780-8562-11ea-88d6-b637d2d333dc.png)

**Comment by timo11** [comment]
I just added code to log main window size info that gets saved to local prefs when specify shuts down and reloaded on start up. Maybe the logs will help us to discern a pattern, or something.

**Comment by timo11** [comment]
The prefs are APP.X, APP.Y, APP.W, APP.H and APP.MAXIMIZED

**Comment by timo11** [comment]
The prefs are in the user.properties file, with the master keys. Not the usage files.

**Comment by maxxxxxdlp** [comment]
Happened again. Logs and preferences are attached. Hope this helps
[data.zip](https://github.com/specify/specify6/files/4645377/data.zip)
[data2.zip](https://github.com/specify/specify6/files/4645378/data2.zip)

**Comment by maxxxxxdlp** [comment]
Happened again

<img width="922" alt="Screen Shot 2020-07-05 at 5 19 15 PM" src="https://user-images.githubusercontent.com/40512816/86534803-0c15f880-bea1-11ea-9e43-fea03169c3d0.png">

I made a small observation:
Specify initially opens up in normal size (covers most of the screen) but immediately after that get's shrunk down to that small window

Here are the Specify folders:
After this bug happened and the window was manually opened in full screen, but before Specify was closed:
[Specify_folder_in_Documents.zip](https://github.com/specify/specify6/files/4875031/Specify_folder_in_Documents.zip)
[Specify_folder_in_user_root_dir.zip](https://github.com/specify/specify6/files/4875032/Specify_folder_in_user_root_dir.zip)

After Specify was fully closed:
[Specify_folder_in_Documents.zip](https://github.com/specify/specify6/files/4875037/Specify_folder_in_Documents.zip)
[Specify_folder_in_user_root_dir.zip](https://github.com/specify/specify6/files/4875038/Specify_folder_in_user_root_dir.zip)

After Specify was opened again (without this bug happening):
[Specify_folder_in_Documents.zip](https://github.com/specify/specify6/files/4875046/Specify_folder_in_Documents.zip)
[Specify_folder_in_user_root_dir.zip](https://github.com/specify/specify6/files/4875048/Specify_folder_in_user_root_dir.zip)

**Comment by maxxxxxdlp** [comment]
Specify opened in a tiny window again
@timo11 I see that you added some logging scripts, so here is the console output:
```
************************ Type: App  Action: StartUp
22:48:06 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
22:48:07 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
22:48:07  INFO brc.specify.Specify:2373 - positionAndFitToScreen(javax.swing.JFrame[frame0,208,55,1024x790,hidden,layout=java.awt.BorderLayout,title=Specify 6.8.00,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,22,1024x768,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true], 25, 28, 1440, 900)
22:48:07 DEBUG specify.config.CheckDBAfterLogin:1362 - Fixed 0/-1
```

**Comment by grantfitzsimmons** [comment]
Wanted to bump this as a reminder this still happens.
